/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interview.rectangle;

import interview.rectangle.model.AdjacentDefinition;
import interview.rectangle.model.ContainmentDefinition;
import interview.rectangle.model.IntersectionDefinition;
import interview.rectangle.model.Rectangle;

public class Library {
    public IntersectionDefinition detectIntersection(Rectangle rectangle1, Rectangle rectangle2) throws Exception {
        return rectangle1.intersects(rectangle2);
    }

    public ContainmentDefinition detectContainment(Rectangle container, Rectangle contained) {
        return container.contains(contained);
    }

    public AdjacentDefinition detectAdjacency(Rectangle rectangle1, Rectangle rectangle2) throws Exception {
        return rectangle1.isAdjacent(rectangle2);
    }
}
